### ISSUE TITLE
Multiple annotation possibility

### ISSUE THREAD

**Issue by ahurriyetoglu** [proycon/flat#28]
By defining a multiple annotation mode, we can mark many items to be annotated as they were annotated individually, separately. This can be for a single type or multiple types batch annotation.

**Comment by proycon** [comment]
Agreed, thinking about it, will implement soon

**Comment by proycon** [comment]
First attempt failed, trying again..

**Comment by proycon** [comment]
Implemented using a "queue" and "repeat" mechanism:
* You can queue actions instead of directly submitting them (queuing is fast as the server is not involved yet). The queue, containing multiple queries, can be submitted using the "Submit queue" button. The contents of the queue (FQL queries) can be inspected in the console window. Select the "queue" checkbox in the editor dialog to use queuing.
* An action can be repeated for the next selected target element. For the next element, Annotation fields will be preset to the same values as the current fields (only changed fields count). Select the "repeat" checkbox in the editor dialog to use this.
